import json
import os
from collections import defaultdict

def print_grouped_names(target_ids):
    # Define path
    base_dir = r'C:\Users\yejun\Desktop\Project\weekly_routine_ai'
    json_path = os.path.join(base_dir, 'data', '02_processed', 'processed_query_result.json')

    # 1. Read the JSON file
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error: {e}")
        return

    # 2. Create a lookup map
    id_to_info_map = {
        item['eTextId']: {
            'bName': item.get('bName', 'N/A'),
            'kName': item.get('kName', 'N/A')
        }
        for item in data if 'eTextId' in item
    }

    # 3. Group the found exercises by bName
    grouped_by_bname = defaultdict(list)
    for target_id in target_ids:
        info = id_to_info_map.get(target_id)
        if info and info['bName'] == "Leg":
            grouped_by_bname[info['bName']].append(target_id)
        # else:
        #     grouped_by_bname['Unknown'].append(f"{target_id} (Not Found)")

    # 4. Print the grouped results
    print("Exercises grouped by body part:")
    for bname, kname_list in grouped_by_bname.items():
        print(f"\n{bname}")
        for kname in kname_list:
            print(f"\"{kname}\"", end=',')

if __name__ == '__main__':
    a = ["BB_BSQT","JUMP_SQT","BB_DL","RM_BB_DL","SM_BB_DL","LUNGE","BB_BP","BB_INC_PRESS","DB_BP","PUSH_UP","WEI_PUSH_UP","DB_INC_BP","CHEST_PRESS_MC","INC_BP_MAC","WEI_PULL_UP","CHIN_UP","WEI_CHIN_UP","BB_LOW","PENDLAY_ROW","INC_BB_ROW","INC_DB_ROW","DB_LOW","OA_DB_ROW","WEI_HPET","HS","BB_CLEAN","BB_CNJ","BB_JERK","BB_SNATCH","BB_OH_SQT","V_SQT","REV_V_SQT","TRAP_DL","BAR_MU","PAUSE_DL","BB_JUMP_SQT","BB_LUNGE","BB_SNATCH_BAL","CLAP_PUSH_UP","DB_SM_SQT","DB_BURPEE","HANG_CLEAN","HANG_SNATCH","CLEAN_HIGH_PULL","SNATCH_HIGH_PULL","KB_DL","KB_SM_DL","DB_SM_DL","DB_LAT_LUNGE","KB_LAT_LUNGE","BB_SM_SQT","PISTOL_SQT","DEFICIT_DL","RACK_PULL","SM_RACK_PULL","BELT_SQT_MC","SAFEBAR_SQT","TRAP_ROW","TRAP_SQT","LEVER_SQT_MC"]
    b = ["BB_BSQT","BB_FSQ","ZER_SQT","BB_SPLIT_SQT","DB_BULSPLIT_SQT","DB_SPLIT_SQT","GOBLET_SQT","KB_GOBLET_SQT","GOOD_MORN","BB_DL","RM_BB_DL","SM_BB_DL","LEG_PRESS","LEG_CURL","LGE_EXT","STD_CALF_RAISE","INN_THIGH_MC","DB_LUNGE","WEI_STEP_UP","WEI_HIP_THRUST","BB_BP","BB_INC_PRESS","DB_BP","WEI_DIPS","DB_FLY","DB_INC_FLY","WEI_PUSH_UP","CROSS_OVER","DB_INC_BP","CHEST_PRESS_MC","PEC_DECK_MC","INC_BP_MAC","DB_PULLOVER","WEI_PULL_UP","WEI_CHIN_UP","BB_LOW","PENDLAY_ROW","INC_BB_ROW","INC_DB_ROW","DB_LOW","OA_DB_ROW","BB_PULLOVER","MC_LOW","SEATED_CABLE_ROW","LAT_PULL_DOWN","WEI_HPET","BB_PRESS","DB_SHD_PRESS","ARNOLD_DB_PRESS","SHD_PRESS_MAC","BB_BHD_NECK_PRESS","DB_F_RAISE","DB_LAT_RAISE","DB_BO_LAT_RAISE","DB_SHRUG","BB_SHRUG","FACE_PULL","CABLE_REV_FLY","BB_UPRIGHT_ROW","DB_UPRIGHT_ROW","EZB_UPRIGHT_ROW","BB_BC_CURL","EZB_CURL","DB_BC_CURL","DB_HAM_CURL","CABLE_CURL","CG_BB_BP","DB_TRI_EXT","SEAT_DB_TRI_EXT","CABLE_TRI_EXT","DB_KICKBACK","BB_WRIST_CURL","EZB_WRIST_CURL","DB_WRIST_CURL","SKULL_CRUSH","LYING_TRI_EXT","CABLE_PUSH_DOWN","RUS_TWIST","DB_SIDE_BEND","BB_CLEAN","BB_CNJ","BB_JERK","BB_SNATCH","PUSH_PRESS","BB_OH_SQT","THRUSTER","KB_SWING","WB_SHOT","V_SQT","REV_V_SQT","T_BAR_ROW_MAC","DB_PREA_CURL","BB_PREA_CURL","EZ_PREA_CURL","PREA_CURL_MAC","REV_PEC_DECK_MC","GLUTE_KB_MC","HIP_ABD_MC","SEAT_DIPS_MC","LAT_RAISE_MC","CABLE_LAT_RAISE","MAG_LAT_PULL_DOWN","PAR_LAT_PULL_DOWN","REV_LAT_PULL_DOWN","SEAT_CALF_RAISE","CABLE_FRONT_RAISE","ARM_CURL_MC","ABS_CRUNCH_MC","PAUSE_SQT","TRAP_DL","DB_SNATCH","KB_SNATCH","SM_PRESS","SM_SPLIT_SQT","SM_DL","SM_ROW","SM_BP","SM_SHRUG","SM_SQT","SM_INC_PRESS","CABLE_CRUNCH","CABLE_HIP_ABD","CABLE_HAM_CURL","CABLE_ARM_PULL_DOWN","LP_CABLE_FLY","CABLE_OHT_EXT","HACK_SQT","HAMMER_BP","SPOTO_BP","PAUSE_DL","PAUSE_SM_DL","PAUSE_BB_ROW","ASS_DIP_MC","ASS_PULLUP_MC","FLOOR_SEATED_ROW","BB_BOX_SQT","BB_DEC_BP","BB_FLOOR_PRESS","BB_FR_LUNGE","BB_FRONT_RAISE","EZB_FRONT_RAISE","BB_JUMP_SQT","BB_LUNGE","BB_LAT_LUNGE","BB_SNATCH_BAL","BB_SPLIT_SQT_REAL","BB_STD_CALF_RAISE","STIFF_DL","CABLE_LYING_TRI_EXT","DB_SM_SQT","DB_BURPEE","DB_DEC_FLY","DB_LEG_CURL","DB_REAR_LAT_RAISE","DB_SQT","DB_THRUSTER","BB_HACK_SQT","WEI_HANG_KNEE_RAISE","HANG_CLEAN","HANG_SNATCH","LAT_WIDE_PULL","SUMO_DEAD_HIGH","KB_SUMO_HIGH","CLEAN_HIGH_PULL","SNATCH_HIGH_PULL","SEAT_LEG_CURL","HIP_THRUST_MAC","DEC_DB_BP","DEC_CHEST_MAC","DB_RM_DL","REV_BB_WRIST_CURL","REV_DB_WRIST_CURL","INC_DB_CURL","WRIST_ROLLER","REV_BB_CURL","REV_BB_ROW","LYING_BB_ROW","INC_DB_TWIST_PRESS","INC_CABLE_FLY","STD_CABLE_FLY","BB_SL_DEAD","DB_SL_DEAD","KB_DL","KB_SM_DL","DB_SM_DL","DB_STIFF_DL","DB_LAT_LUNGE","KB_LAT_LUNGE","SL_LEG_EXT","SL_LEG_CURL","SL_LEG_PRESS","HZ_LEG_PRESS","HZ_SL_LEG_PRESS","SEAT_SL_LEG_CURL","NOR_HAM_CURL","BB_SM_SQT","KB_SM_SQT","SEAT_BB_SHD_PRESS","SEAT_DB_SHD_PRESS","PLATE_SHD_PRESS","TRI_EXT_MC","BHD_NECK_PULL_DOWN","CABLE_OA_PULL_DOWN","OA_LAT_WIDE_PULL_DOWN","DB_Y_RAISE","LOW_ROW_MC","OA_LOW_ROW_MC","HIGH_ROW_MC","UNDER_HIGH_ROW_MC","OA_HIGH_ROW_MC","SHRUG_MC","CABLE_SHRUG","CABLE_DONK_KICK","CABLE_SIDE_BEND","WEI_DEC_CRUNCH","WEI_DEC_SIT_UP","DEFICIT_DL","TURKISH_GET_UP","KB_LUNGE_TWIST","INC_CHEST_PRESS_MC","CABLE_TWIST","CABLE_PULL_THRU","CABLE_INT_ROT","CABLE_EXT_ROT","OA_CABLE_LAT_RAISE","OA_CABLE_SEATED_ROW","DB_SQUEEZE_PRESS","LAND_PRESS","OA_LAND_PRESS","MON_GLUTE_MC","WEI_ABS_HIP_THRU","CABLE_BO_LAT_RAISE","CABLE_UPRIGHT_ROW","OA_DB_LAT_RAISE","HAND_GRIPPER","TORSO_ROT_MC","RACK_PULL","SM_RACK_PULL","STD_MULTI_FLIGHT_MC","INC_DB_REAR_LAT_RAISE","KB_SHD_PRESS","OA_KB_SHD_PRESS","OA_DB_INC_LAT_RAISE","INC_DB_SHD_PRESS","PEND_SQT","BO_LAT_RAISE_MC","CABLE_ROPE_PUSH_DOWN","LIN_HACK_SQT_MC","STD_OH_PRESS_MC","SM_CALF_RAISE","DB_STD_CALF_RAISE","MID_ROW_MC","CONCENT_CURL","SIDE_LYING_REAR_RAISE","SIDE_LYING_LAT_RAISE","BACK_ET_MC","BB_BACK_LUNGE","KB_BACK_LUNGE","BP_MC","BB_JM_PRESS","SM_JM_PRESS","STD_HAM_CURL_MC","INC_BB_FR_RAISE","INC_EZ_FRONT_RAISE","INC_DB_FRONT_RAISE","BB_INC_FRONT_RAISE","EZ_INC_FRONT_RAISE","DB_INC_FRONT_RAISE","EZ_REVERSE_CURL","PLATE_FRONT_RR","PG_WEIGHTED_PULL_UP","EZ_TRI_EXT","SEAT_DB_LAT_RAISE","CG_SM_BP","EZ_BHD_WRIST_CURL","OA_DB_WRIST_CURL","OA_CABLE_FLY","CABLE_BP","SM_BULSPLIT_SQT","ALTER_DB_BP","BELT_SQT_MC","SAFEBAR_SQT","INC_DB_PULL_OVER","DB_LYING_TRI_EXT","EZ_LYING_TRI_EXT","FEETUP_BP","AB_COASTER_MC","OA_CABLE_LAT_PULL_DOWN","RG_BP","INC_DB_HAMMER_CURL","LYING_CABLE_PULL_OVER","SM_UPRIGHT_ROW","SM_HIP_THRUSTER","SM_BHD_NECK_PRESS","PAUSED_BP","STD_LAT_RAISE_MC","DB_SKULL_CRUSH","SEAT_BB_TRI_EXT","STD_CABLE_ROW","TRAP_ROW","TRAP_SQT","TRAP_OHP","BICEP_CURL_MC","CHEST_FLY_MC","DY_ROW_MC","DB_FRONT_SQT","BHD_WRIST_CURL","TRI_PRESS_MC","INN_CHEST_MC","OA_KB_ROW","HP_CABLE_ROW","BOSU_DB_OL_DL","LEVER_SQT_MC","CG_LAT_PULL_DOWN","OA_DB_CURL","OA_DB_HAM_CURL","REV_EZ_WRIST_CURL","OA_FACE_PULL","ROTARY_CALF","BB_INC_REAR_ROW","HP_OA_CABLE_ROW","LP_OA_CABLE_ROW","KB_OL_DL","OA_KB_SWING","LP_CABLE_ROPE_ROW","SEAT_CABLE_FLY","SEAT_CABLE_RL_RAISE","CABLE_RL_RAISE","DB_WRIST_SUPI","DB_WRIST_RAD_FLEX","CHEST_SUP_T_ROW"]
    ids_to_find = list(set(a) & set(b))
    # print(ids_to_find)
    print_grouped_names(ids_to_find)

